import { SafetyCertificateOutlined } from '@ant-design/icons';

export default {
  ACCOUNT: 'profile',
  ADD: 'plus',
  ACTIVITY: 'pushpin',
  CAMPAIGN: 'campaign',
  CANCEL: 'close',
  DEFAULT: 'minus',
  DELEGATE: SafetyCertificateOutlined,
  DELETE: 'delete',
  EDIT: 'edit',
  FOLLOWERS: ' plus',
  INVITE: 'invite',
  INTEGRATION: 'link',
  LISK: 'lisk',
  IDEA: 'thunderbolt',
  LEFT: 'left',
  MAINNET: 'rocket',
  MEDIA: 'camera',
  NETWORK: 'global',
  NO_CAMPAIGN: 'no-campaign',
  OPTIONS: 'ellipsis',
  OVERVIEW: 'appstore',
  PHASE: 'compass',
  PLATFORM: 'global',
  PROJECT: 'project',
  PROMISE: 'trophy',
  ROADMAP: 'ordered-list',
  SETTINGS: 'setting',
  SIDECHAIN: 'fork',
  TESTNET: 'experiment',
  TEAM: 'team',
  TOOL: 'layout',
  USER: 'user'
}
